version: "2.1"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb
    env_file:
        - creds.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./config:/config
    ports:
      - 3306:3306
    restart: unless-stopped
  express:
    build: ./server
    depends_on:
        - mariadb
    ports:
        - '5000:5000'
  react:
    build: ./client
    depends_on: 
        - express
    ports:
        - '3000:3000'